### ISSUE TITLE
Double-click crashes focal

### ISSUE THREAD

**Issue by kstenschke** [ohwgiles/focal#45]
Double-clicking on a cell causes focal to crash with a "segmentation fault (core dumped)" error

**Comment by ohwgiles** [comment]
I think this happens when you have no calendars defined (or shown), and it's due to [this code](https://github.com/ohwgiles/focal/blob/62896e32fdca63a288f34356c0775288289b0fe6/src/week-view.c#L306-L307). A quick fix would be to do nothing if there are no items in the `wv->calendars` list. As part of a more complete solution, the user needs a way to select which calendar the new event will be attached to, but I'd prefer to treat that as a separate enhancement issue.

**Comment by kstenschke** [comment]
i will have a look at it than and send a PR, thanks for pointing me to the probably related code already.
